INFO 2020-09-01 06:31:24,157 contacts_logger views 12051 140669177218816 Logger Work
INFO 2020-09-01 06:31:51,224 contacts_logger views 12139 140104464643840 Logger Work
INFO 2020-09-01 06:32:02,255 contacts_logger views 12178 139834132367104 Logger Work
INFO 2020-09-01 06:38:44,127 contacts_logger views 12866 140228165138176 Logger Work
WARNING 2020-09-01 06:39:06,320 django.request log 12866 140228064966400 Not Found: /favicon.ico
WARNING 2020-09-01 06:39:06,322 django.server basehttp 12866 140228064966400 "GET /favicon.ico HTTP/1.1" 404 2439
INFO 2020-09-01 06:39:25,619 contacts_logger views 13032 139821187720960 Logger Work
INFO 2020-09-01 06:40:22,077 contacts_logger views 13177 139809363248896 Logger Work
INFO 2020-09-01 06:46:43,277 contacts_logger views 13946 139728043849472 Logger Work
INFO 2020-09-01 06:48:00,452 contacts_logger views 14081 140243254982400 Logger Work
INFO 2020-09-01 06:48:40,989 contacts_logger views 14157 140267130349312 Logger Work
INFO 2020-09-01 06:49:05,083 contacts_logger views 14226 140131441641216 Logger Work
INFO 2020-09-01 06:49:46,548 contacts_logger views 14342 140094052640512 Logger Work
INFO 2020-09-01 06:52:50,096 contacts_logger views 14746 139987938596608 Logger Work
INFO 2020-09-01 06:53:15,930 contacts_logger views 14817 140134111901440 Logger Work
WARNING 2020-09-01 06:54:24,521 django.request log 14817 140134081451776 Not Found: /token/
WARNING 2020-09-01 06:54:24,524 django.server basehttp 14817 140134081451776 "POST /token/ HTTP/1.1" 404 2425
WARNING 2020-09-01 06:54:46,784 django.request log 14817 140134081451776 Bad Request: /api/token/
WARNING 2020-09-01 06:54:46,788 django.server basehttp 14817 140134081451776 "POST /api/token/ HTTP/1.1" 400 76
WARNING 2020-09-01 06:55:00,101 django.request log 14817 140134081451776 Bad Request: /api/token/
WARNING 2020-09-01 06:55:00,103 django.server basehttp 14817 140134081451776 "POST /api/token/ HTTP/1.1" 400 76
WARNING 2020-09-01 06:55:11,326 django.request log 14817 140134081451776 Bad Request: /api/token/
WARNING 2020-09-01 06:55:11,328 django.server basehttp 14817 140134081451776 "POST /api/token/ HTTP/1.1" 400 76
ERROR 2020-09-01 06:55:20,975 django.request log 14817 140134081451776 Internal Server Error: /api/token
Traceback (most recent call last):
  File "/home/gwl/Desktop/Dfuzr/POC/contact/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/gwl/Desktop/Dfuzr/POC/contact/venv/lib/python3.7/site-packages/django/utils/deprecation.py", line 90, in __call__
    response = self.process_request(request)
  File "/home/gwl/Desktop/Dfuzr/POC/contact/venv/lib/python3.7/site-packages/django/middleware/common.py", line 53, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/gwl/Desktop/Dfuzr/POC/contact/venv/lib/python3.7/site-packages/django/middleware/common.py", line 93, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/api/token/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2020-09-01 06:55:20,981 django.server basehttp 14817 140134081451776 "POST /api/token HTTP/1.1" 500 71315
WARNING 2020-09-01 06:55:34,082 django.request log 14817 140134081451776 Bad Request: /api/token/
WARNING 2020-09-01 06:55:34,085 django.server basehttp 14817 140134081451776 "POST /api/token/ HTTP/1.1" 400 76
WARNING 2020-09-01 06:56:05,892 django.request log 14817 140134081451776 Bad Request: /api/token/
WARNING 2020-09-01 06:56:05,895 django.server basehttp 14817 140134081451776 "POST /api/token/ HTTP/1.1" 400 76
WARNING 2020-09-01 08:09:51,922 django.request log 14817 140134081451776 Method Not Allowed: /api/token/
WARNING 2020-09-01 08:09:51,922 django.server basehttp 14817 140134081451776 "GET /api/token/ HTTP/1.1" 405 40
WARNING 2020-09-01 08:09:56,543 django.request log 14817 140134081451776 Bad Request: /api/token/
WARNING 2020-09-01 08:09:56,543 django.server basehttp 14817 140134081451776 "POST /api/token/ HTTP/1.1" 400 76
WARNING 2020-09-01 08:11:08,180 django.request log 14817 140134081451776 Method Not Allowed: /api/token/verify/
WARNING 2020-09-01 08:11:08,180 django.server basehttp 14817 140134081451776 "GET /api/token/verify/ HTTP/1.1" 405 40
WARNING 2020-09-01 08:11:12,479 django.request log 14817 140134081451776 Bad Request: /api/token/verify/
WARNING 2020-09-01 08:11:12,479 django.server basehttp 14817 140134081451776 "POST /api/token/verify/ HTTP/1.1" 400 37
WARNING 2020-09-01 08:11:31,257 django.request log 14817 140134081451776 Unsupported Media Type: /api/token/verify/
WARNING 2020-09-01 08:11:31,257 django.server basehttp 14817 140134081451776 "POST /api/token/verify/ HTTP/1.1" 415 74
WARNING 2020-09-01 08:11:37,428 django.request log 14817 140134081451776 Bad Request: /api/token/verify/
WARNING 2020-09-01 08:11:37,428 django.server basehttp 14817 140134081451776 "POST /api/token/verify/ HTTP/1.1" 400 37
WARNING 2020-09-01 08:11:59,910 django.request log 14817 140134081451776 Bad Request: /api/token/verify/
WARNING 2020-09-01 08:11:59,910 django.server basehttp 14817 140134081451776 "POST /api/token/verify/ HTTP/1.1" 400 109
ERROR 2020-09-01 08:13:12,935 django.request log 14817 140134081451776 Internal Server Error: /api/hello
Traceback (most recent call last):
  File "/home/gwl/Desktop/Dfuzr/POC/contact/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/gwl/Desktop/Dfuzr/POC/contact/venv/lib/python3.7/site-packages/django/utils/deprecation.py", line 90, in __call__
    response = self.process_request(request)
  File "/home/gwl/Desktop/Dfuzr/POC/contact/venv/lib/python3.7/site-packages/django/middleware/common.py", line 53, in process_request
    path = self.get_full_path_with_slash(request)
  File "/home/gwl/Desktop/Dfuzr/POC/contact/venv/lib/python3.7/site-packages/django/middleware/common.py", line 93, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/api/hello/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2020-09-01 08:13:12,935 django.server basehttp 14817 140134081451776 "POST /api/hello HTTP/1.1" 500 71315
WARNING 2020-09-01 08:13:34,011 django.request log 14817 140134081451776 Unauthorized: /api/hello/
WARNING 2020-09-01 08:13:34,011 django.server basehttp 14817 140134081451776 "GET /api/hello/ HTTP/1.1" 401 58
WARNING 2020-09-01 08:14:02,108 django.request log 14817 140134081451776 Unauthorized: /api/hello/
WARNING 2020-09-01 08:14:02,108 django.server basehttp 14817 140134081451776 "GET /api/hello/ HTTP/1.1" 401 58
WARNING 2020-09-01 08:14:31,061 django.request log 14817 140134081451776 Unauthorized: /api/hello/
WARNING 2020-09-01 08:14:31,062 django.server basehttp 14817 140134081451776 "GET /api/hello/ HTTP/1.1" 401 176
WARNING 2020-09-01 08:15:26,756 django.request log 14817 140134081451776 Unauthorized: /api/hello/
WARNING 2020-09-01 08:15:26,756 django.server basehttp 14817 140134081451776 "GET /api/hello/ HTTP/1.1" 401 176
INFO 2020-09-01 08:19:33,393 contacts_logger views 18984 139856624609024 Logger Work
INFO 2020-09-01 08:55:56,244 contacts_logger views 23024 139762892318464 Logger Work
